export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const SAVE_ID_TO_FAVS = "SAVE_ID_TO_FAVS";
export const REMOVE_ID_FROM_FAVS = "REMOVE_ID_FROM_FAVS";
